name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_job:
    runs-on: windows-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: choco install docfx
        run: |
          choco install docfx --pre -y
        env:
          CI: true
      - name: build metadata -f
        run: |
          docfx metadata
      - name: build documentation
        run: |
          docfx build -t default,templates/slc_template -f
      - name: publish results
        uses: actions/upload-artifact@v2.2.4
        with:
          name: _site
          path: _site/
          
  deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build_job
    name: Deploy Job
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: _site
          path: _site 
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_SEA_0E7978F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/_site" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
  
  
  deploy_job_Storage_Account:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build_job
    name: Deploy Job to Storage account
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: _site
          path: _site
      - name: Upload the new files
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: _site
          container_name: docs
          connection_string: ${{ secrets.AZURE_STORAGE_ACCOUNT_DOCS_CONNECTION_STRING }}
          # Sync: true keeps the source and destination in sync,
          # otherwise changed files and new would be pushed, but deleted wouldn't be removed.
          sync: 'true'
          
  reindex_azure_search:
    runs-on: ubuntu-latest
    needs: deploy_job_Storage_Account
    name: Re-index azure search
    steps:
    - name: Azure Cognitive Search Reindex
      # You may pin to the exact commit or the version.
      # uses: andrewconnell/azure-search-index@ac64a40924771a415e01d52db4c1d557ecd3a99f
      uses: andrewconnell/azure-search-index@1.0.1
      with:
        # Name of the Azure Cognitive Search resource.
        azure-search-instance: srch-docs-001
        # Search indexer to reindex
        azure-search-indexer: docs-indexer-001
        # Admin key used to connect to Azure Cognitive Search instance
        azure-search-admin-key: ${{ secrets.AZURE_SEARCH_ADMIN_KEY_INDEXER }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_SEA_0E7978F03 }}
          action: "close"
